name = "smzase-sub-web"
main = "worker/index.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "subKV"
id = "subKV"

[[r2_buckets]]
binding = "R2"
bucket_name = "smzase-fonts"
