name = "smzasesub-web"
main = "worker/index.ts"
compatibility_date = "2026-5-10"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "subKV"
id = "fe0e970234e14934b33ce96bdd98a5b6"

[[r2_buckets]]
binding = "R2"
bucket_name = "smzase-fonts"
